id: P003087
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN8147
  title: སྒོ་བཞི་མཛོད་ལྔའི་ཡང་བཅུད།_(33-50)
  author: ''
  volumes:
    4c7f5dc0148c41d0b59284c3cb60fe52:
      image_group_id: I3CN8149
      title: ''
      volume_number: 1
      total_pages: 0
    fd15604782f745368fc017c35fdd0ae6:
      image_group_id: I3CN8150
      title: ''
      volume_number: 2
      total_pages: 0
    bcbd1ec0a95a450c80c1597c91181ac1:
      image_group_id: I3CN8151
      title: ''
      volume_number: 3
      total_pages: 0
    22f56c1d586547d9b7b2ef5b3ceec2ba:
      image_group_id: I3CN8152
      title: ''
      volume_number: 4
      total_pages: 0
    db08d02e36124b488fb96d85a896e119:
      image_group_id: I3CN8153
      title: ''
      volume_number: 5
      total_pages: 0
    830629b065654eb7aacbf97c1853243b:
      image_group_id: I3CN8154
      title: ''
      volume_number: 6
      total_pages: 0
    1f4ac103571a45e1ad7ee5b9be3791ab:
      image_group_id: I3CN8155
      title: ''
      volume_number: 7
      total_pages: 0
    24e8bb4dfd3b481e971da22659bd61f4:
      image_group_id: I3CN8156
      title: ''
      volume_number: 8
      total_pages: 0
    1c584377b0154036b68e16db628ce644:
      image_group_id: I3CN8157
      title: ''
      volume_number: 9
      total_pages: 0
    b50bbe4c2a294d39af8bdce01ccee35e:
      image_group_id: I3CN8158
      title: ''
      volume_number: 10
      total_pages: 0
    4ff44f623251463b95e5f102c7a71635:
      image_group_id: I3CN8159
      title: ''
      volume_number: 11
      total_pages: 0
    9aa30004c06d47a6bca890ee8cbfdd1d:
      image_group_id: I3CN8160
      title: ''
      volume_number: 12
      total_pages: 0
    f87ca0f52336423984c86e14563bea61:
      image_group_id: I3CN8161
      title: ''
      volume_number: 13
      total_pages: 0
    e9aec4f3d33e4fe4ae40482b3d8e76bc:
      image_group_id: I3CN8162
      title: ''
      volume_number: 14
      total_pages: 0
    22a2b427e89d4f4480c9291732667eb6:
      image_group_id: I3CN8163
      title: ''
      volume_number: 15
      total_pages: 0
    96d96af8b0294a05b9b8544b813dfbab:
      image_group_id: I3CN8164
      title: ''
      volume_number: 16
      total_pages: 534
    9f63bfec653546f3bac6d029e1800ed9:
      image_group_id: I3CN8165
      title: ''
      volume_number: 17
      total_pages: 330
    f76ebb48be1b4920842447129a6479dd:
      image_group_id: I3CN8166
      title: ''
      volume_number: 18
      total_pages: 335
