id: I715A5175
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T02:59:48+00:00'
last_modified: '2022-06-07T17:28:23.532746+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN8147
  title: སྒོ་བཞི་མཛོད་ལྔའི་ཡང་བཅུད།_(33-50)
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '3796':
      image_group_id: I3CN8149
      title: ''
      total_pages: 0
      order: 1
      base_file: 3796.txt
    '4432':
      image_group_id: I3CN8150
      title: ''
      total_pages: 0
      order: 2
      base_file: 4432.txt
    0A33:
      image_group_id: I3CN8151
      title: ''
      total_pages: 0
      order: 3
      base_file: 0A33.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
